#!/bin/sh
set -e

# Automatically added by dh_python2:
if which pyclean >/dev/null 2>&1; then
	pyclean -p freecad 
else
	dpkg -L freecad | grep \.py$ | while read file
	do
		rm -f "${file}"[co] >/dev/null
  	done
fi
# End automatically added section
